%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-jsk-pcl-ros
Version:        1.2.11
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS jsk_pcl_ros package

License:        BSD
URL:            https://jsk-docs.readthedocs.io/projects/jsk_recognition/en/latest/jsk_pcl_ros
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       boost-python3-devel
Requires:       python3-scikit-learn
Requires:       ros-noetic-checkerboard-detector
Requires:       ros-noetic-cv-bridge
Requires:       ros-noetic-diagnostic-msgs
Requires:       ros-noetic-diagnostic-updater
Requires:       ros-noetic-dynamic-reconfigure
Requires:       ros-noetic-eigen-conversions
Requires:       ros-noetic-geometry-msgs
Requires:       ros-noetic-image-geometry
Requires:       ros-noetic-image-transport
Requires:       ros-noetic-image-view2
Requires:       ros-noetic-interactive-markers
Requires:       ros-noetic-jsk-data
Requires:       ros-noetic-jsk-footstep-msgs
Requires:       ros-noetic-jsk-pcl-ros-utils
Requires:       ros-noetic-jsk-recognition-msgs
Requires:       ros-noetic-jsk-recognition-utils
Requires:       ros-noetic-jsk-topic-tools >= 2.2.7
Requires:       ros-noetic-kdl-conversions
Requires:       ros-noetic-kdl-parser
Requires:       ros-noetic-laser-assembler
Requires:       ros-noetic-moveit-core
Requires:       ros-noetic-moveit-ros-perception
Requires:       ros-noetic-nav-msgs
Requires:       ros-noetic-nodelet
Requires:       ros-noetic-octomap
Requires:       ros-noetic-octomap-server
Requires:       ros-noetic-openni2-launch
Requires:       ros-noetic-pcl-conversions
Requires:       ros-noetic-pcl-msgs
Requires:       ros-noetic-pcl-ros
Requires:       ros-noetic-resized-image-transport
Requires:       ros-noetic-robot-self-filter
Requires:       ros-noetic-rosboost-cfg
Requires:       ros-noetic-roscpp-tutorials
Requires:       ros-noetic-sensor-msgs
Requires:       ros-noetic-std-msgs
Requires:       ros-noetic-std-srvs
Requires:       ros-noetic-stereo-image-proc
Requires:       ros-noetic-stereo-msgs
Requires:       ros-noetic-tf
Requires:       ros-noetic-tf-conversions
Requires:       ros-noetic-tf2-ros
Requires:       ros-noetic-topic-tools
Requires:       ros-noetic-visualization-msgs
Requires:       yaml-cpp-devel
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-cv-bridge
BuildRequires:  ros-noetic-image-geometry
BuildRequires:  ros-noetic-image-transport
BuildRequires:  ros-noetic-interactive-markers
BuildRequires:  ros-noetic-jsk-data
BuildRequires:  ros-noetic-jsk-pcl-ros-utils
BuildRequires:  ros-noetic-jsk-perception
BuildRequires:  ros-noetic-jsk-recognition-utils
BuildRequires:  ros-noetic-jsk-tools
BuildRequires:  ros-noetic-jsk-topic-tools >= 2.2.7
BuildRequires:  ros-noetic-kdl-parser
BuildRequires:  ros-noetic-laser-assembler
BuildRequires:  ros-noetic-moveit-ros-perception
BuildRequires:  ros-noetic-octomap-server
BuildRequires:  ros-noetic-pcl-msgs
BuildRequires:  ros-noetic-pcl-ros
BuildRequires:  ros-noetic-roslaunch
BuildRequires:  ros-noetic-rostest
BuildRequires:  ros-noetic-tf
BuildRequires:  ros-noetic-tf-conversions
BuildRequires:  yaml-cpp-devel
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
ROS nodelets for pointcloud perception.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Thu Oct 01 2020 Youhei Kakiuchi <youhei@jsk.t.u-tokyo.ac.jp> - 1.2.11-1
- Autogenerated by Bloom

