Name:           ros-melodic-jsk-perception
Version:        1.2.10
Release:        0%{?dist}
Summary:        ROS jsk_perception package

Group:          Development/Libraries
License:        BSD
URL:            http://jsk-docs.readthedocs.io/en/latest/jsk_recognition/doc/jsk_perception
Source0:        %{name}-%{version}.tar.gz

Requires:       PyYAML
Requires:       eigen3-devel
Requires:       h5py
Requires:       libleveldb-devel
Requires:       python-scikit-learn
Requires:       ros-melodic-angles
Requires:       ros-melodic-cv-bridge
Requires:       ros-melodic-dynamic-reconfigure
Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-image-geometry
Requires:       ros-melodic-image-transport
Requires:       ros-melodic-image-view
Requires:       ros-melodic-image-view2
Requires:       ros-melodic-imagesift
Requires:       ros-melodic-jsk-data
Requires:       ros-melodic-jsk-gui-msgs
Requires:       ros-melodic-jsk-recognition-msgs
Requires:       ros-melodic-jsk-recognition-utils
Requires:       ros-melodic-jsk-topic-tools
Requires:       ros-melodic-libcmt
Requires:       ros-melodic-message-runtime
Requires:       ros-melodic-mk
Requires:       ros-melodic-nodelet
Requires:       ros-melodic-opencv-apps
Requires:       ros-melodic-openni2-launch
Requires:       ros-melodic-pcl-ros
Requires:       ros-melodic-posedetection-msgs
Requires:       ros-melodic-robot-self-filter
Requires:       ros-melodic-rosbag
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-roseus
Requires:       ros-melodic-rospack
Requires:       ros-melodic-rospy
Requires:       ros-melodic-rostopic
Requires:       ros-melodic-rqt-gui
Requires:       ros-melodic-rviz
Requires:       ros-melodic-sensor-msgs
Requires:       ros-melodic-sound-play
Requires:       ros-melodic-std-msgs
Requires:       ros-melodic-tf
Requires:       yaml-cpp-devel
BuildRequires:  eigen3-devel
BuildRequires:  git
BuildRequires:  ros-melodic-angles
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-cmake-modules
BuildRequires:  ros-melodic-cv-bridge
BuildRequires:  ros-melodic-dynamic-reconfigure
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-image-geometry
BuildRequires:  ros-melodic-image-transport
BuildRequires:  ros-melodic-image-view2
BuildRequires:  ros-melodic-jsk-data
BuildRequires:  ros-melodic-jsk-recognition-msgs
BuildRequires:  ros-melodic-jsk-recognition-utils
BuildRequires:  ros-melodic-jsk-tools
BuildRequires:  ros-melodic-jsk-topic-tools
BuildRequires:  ros-melodic-libcmt
BuildRequires:  ros-melodic-message-generation
BuildRequires:  ros-melodic-mk
BuildRequires:  ros-melodic-nodelet
BuildRequires:  ros-melodic-opencv-apps
BuildRequires:  ros-melodic-pcl-ros
BuildRequires:  ros-melodic-posedetection-msgs
BuildRequires:  ros-melodic-robot-self-filter
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-roseus
BuildRequires:  ros-melodic-roslaunch
BuildRequires:  ros-melodic-roslint
BuildRequires:  ros-melodic-rospack
BuildRequires:  ros-melodic-rostest
BuildRequires:  ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-std-msgs
BuildRequires:  ros-melodic-tf
BuildRequires:  yaml-cpp-devel

%description
ROS nodes and nodelets for 2-D image perception.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Wed Mar 27 2019 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.2.10-0
- Autogenerated by Bloom

* Sat Feb 23 2019 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.2.9-0
- Autogenerated by Bloom

* Thu Feb 14 2019 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.2.7-2
- Autogenerated by Bloom

