Name:           ros-melodic-imagesift
Version:        1.2.9
Release:        0%{?dist}
Summary:        ROS imagesift package

Group:          Development/Libraries
License:        LGPL
URL:            http://jsk-docs.readthedocs.io/en/latest/jsk_recognition/doc/imagesift
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-cv-bridge
Requires:       ros-melodic-image-transport
Requires:       ros-melodic-jsk-recognition-utils
Requires:       ros-melodic-jsk-topic-tools >= 2.2.8
Requires:       ros-melodic-libsiftfast
Requires:       ros-melodic-nodelet
Requires:       ros-melodic-posedetection-msgs
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-cmake-modules
BuildRequires:  ros-melodic-cv-bridge
BuildRequires:  ros-melodic-image-transport
BuildRequires:  ros-melodic-jsk-recognition-utils
BuildRequires:  ros-melodic-jsk-topic-tools >= 2.2.8
BuildRequires:  ros-melodic-libsiftfast
BuildRequires:  ros-melodic-nodelet
BuildRequires:  ros-melodic-posedetection-msgs
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-rostest
BuildRequires:  ros-melodic-sensor-msgs

%description
For every image, computes its sift features and send a new message with the
image, its intrinsic parameters, and the features. Parameters include: display -
shows the image on the local computer

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Sat Feb 23 2019 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.2.9-0
- Autogenerated by Bloom

* Thu Feb 14 2019 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.2.7-2
- Autogenerated by Bloom

